"""Generate a compact LVGL Pinyin dictionary from the GB2312 character set."""

from collections import defaultdict
from pathlib import Path

from pypinyin import Style, pinyin


ROOT = Path(__file__).resolve().parents[1]

# Candidate order matters on a small screen. Put high-frequency simplified
# Chinese characters first, then retain the remaining GB2312 characters.
FREQUENT = (
    "的一是不了人我在有他这为之大来以个中上们到说国和地也子时道出而要"
    "于就下得可你年生自会那后能对着事其里所去行过家十用发天如然作方"
    "成者多日都三小二无同么经法当起与好看学进种将还分此心前面又定见"
    "只主没公从已工使情明性知全理才等外名想原把应美实做点水高长次本"
    "月话常正四先向别体很最女真现新通力间手回重爱更身间气关问意动"
)


def gb2312_chars():
    seen = set()
    for high in range(0xB0, 0xF8):
        for low in range(0xA1, 0xFF):
            try:
                char = bytes((high, low)).decode("gb2312")
            except UnicodeDecodeError:
                continue
            if len(char) == 1 and char not in seen:
                seen.add(char)
                yield char


def pronunciations(char):
    values = pinyin(char, style=Style.NORMAL, heteronym=True,
                    errors="ignore", strict=False)
    if not values:
        return []
    result = []
    for value in values[0]:
        value = value.lower().replace("ü", "v").replace("u:", "v")
        if value.isascii() and value.isalpha() and value[0] not in "iuv":
            result.append(value)
    return result


def main():
    ordered = []
    seen = set()
    for char in FREQUENT:
        if char not in seen:
            ordered.append(char)
            seen.add(char)
    for char in gb2312_chars():
        if char not in seen:
            ordered.append(char)
            seen.add(char)

    groups = defaultdict(list)
    group_seen = defaultdict(set)
    for char in ordered:
        for py in pronunciations(char):
            if char not in group_seen[py]:
                groups[py].append(char)
                group_seen[py].add(char)

    header = '''#pragma once

#include "lvgl.h"

extern const lv_pinyin_dict_t novel_pinyin_dict[];
'''
    lines = [
        "/* Generated by tools/build_pinyin_dict.py; do not hand edit. */",
        '#include "pinyin_dict.h"',
        "",
        "const lv_pinyin_dict_t novel_pinyin_dict[] = {",
    ]
    for py in sorted(groups):
        lines.append(f'    {{ "{py}", "{"".join(groups[py])}" }},')
    lines.extend(["    { NULL, NULL },", "};", ""])

    (ROOT / "main" / "pinyin_dict.h").write_text(header, encoding="utf-8")
    (ROOT / "main" / "pinyin_dict.c").write_text("\n".join(lines),
                                                   encoding="utf-8")
    print(f"Generated {len(groups)} syllables from {len(ordered)} characters")


if __name__ == "__main__":
    main()
